SELECT 
    CITY,
    LENGTH(CITY)
FROM 
    STATION
WHERE 
    LENGTH(CITY) = (SELECT MIN(LENGTH(CITY)) FROM STATION)
GROUP BY CITY
LIMIT 1;

SELECT 
    CITY,
    LENGTH(CITY)
FROM 
    STATION
WHERE 
    LENGTH(CITY) = (SELECT MAX(LENGTH(CITY)) FROM STATION)
GROUP BY CITY
LIMIT 1;

-- returns the two smallest and largest city names from a table named station